
spring.datasource.url=jdbc:postgresql://localhost:5433/gym_db
spring.datasource.username=gym_user
spring.datasource.password=gym_pass
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=QmFzZTY0U2VjcmV0S2V5Rm9yR3ltQXBwMTIzNDU2Nzg5MA==



spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true 


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=EMAIL_TAU@gmail.com
spring.mail.password=APP_PASSWORD_TAU
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.url=http://localhost:5173
app.backend.url=http://localhost:8080